name: Deploy to Supabase & Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  supabase-migrations:
    name: Push Supabase Migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Authenticate Supabase CLI
        working-directory: supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Push Database Migrations
        working-directory: supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase db push --password "$SUPABASE_DB_PASSWORD" --linked --yes

  vercel-deploy:
    name: Deploy Vercel Production Build
    runs-on: ubuntu-latest
    needs: supabase-migrations
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Dependencies
        working-directory: frontend
        run: npm ci

      - name: Pull Vercel Environment
        working-directory: frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN --project=applications-tracker --scope=team_08YYYF8jyDBDsJNqpZyv7ys0

      - name: Build Production Bundle
        working-directory: frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        working-directory: frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
