name: Deploy to Supabase & Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  supabase-migrations:
    name: Push Supabase Migrations
    runs-on: ubuntu-latest
    env:
      SUPABASE_PROJECT_REF: kswjftmtiuwplqtdwqpn
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Push Database Migrations
        working-directory: supabase
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -n "$SUPABASE_DB_URL" ]; then
            DB_URL="$SUPABASE_DB_URL"
          elif [ -n "$SUPABASE_DB_PASSWORD" ]; then
            DB_URL=$(python - <<'PY'
import os, urllib.parse
password = os.environ["SUPABASE_DB_PASSWORD"]
project = os.environ["SUPABASE_PROJECT_REF"]
print(f"postgresql://postgres:{urllib.parse.quote(password)}@db.{project}.supabase.co:5432/postgres")
PY
)
          else
            echo "Supabase connection secrets missing. Set SUPABASE_DB_URL or SUPABASE_DB_PASSWORD." >&2
            exit 1
          fi

          supabase db push --db-url "$DB_URL"

  vercel-deploy:
    name: Deploy Vercel Production Build
    runs-on: ubuntu-latest
    needs: supabase-migrations
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Dependencies
        working-directory: frontend
        run: npm ci

      - name: Pull Vercel Environment
        working-directory: frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN --project=applications-tracker --scope=team_08YYYF8jyDBDsJNqpZyv7ys0

      - name: Build Production Bundle
        working-directory: frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        working-directory: frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
